#!/usr/bin/env bash
# Remove files left over from earlier versions of this project.
#
#   ./cleanup.sh          show what would be removed
#   ./cleanup.sh --apply  actually remove it
#
# Nothing here touches academy.db, .env, photos/ or your source files.

set -u
cd "$(dirname "$0")"

APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

dim=$'\033[2m'; grn=$'\033[32m'; ylw=$'\033[33m'; off=$'\033[0m'
total=0

drop() {
  local path="$1" why="$2"
  [ -e "$path" ] || return 0
  local size
  size=$(du -sh "$path" 2>/dev/null | cut -f1)
  printf "  %s%-34s%s %s%s%s\n" "$ylw" "$path" "$off" "$dim" "$why" "$off"
  printf "  %s%34s  %s%s\n" "$dim" "" "$size" "$off"
  total=$((total+1))
  [ "$APPLY" = "1" ] && rm -rf "$path"
}

echo
echo "  Leftovers from earlier versions"
echo "  -------------------------------"

# From the first, simpler entry system this project grew out of.
drop "entry.db"      "database of the old entry system, unused"
drop "run.bat"       "old launcher, replaced by START.bat"
drop "run.sh"        "old launcher, replaced by start.sh"
drop "entry.db-wal"  "old database journal"
drop "entry.db-shm"  "old database journal"
drop "issue_card.py" "replaced by the Cards page in the app"
drop "reissue.py"    "replaced by the Cards page in the app"
drop "test_flow.py"  "tested the old entry system, not this one"
drop "auth.py"       "authentication was removed"
drop "admin_routes.py" "folded into server.py when auth was removed"
drop "static/admin.js" "admin console was removed"
drop "static/login.html" "authentication was removed"

# Generated by an earlier command-line PyInstaller run. academy.spec is the
# one that is actually used and kept in the repo.
drop "MB Ballet Academy.spec" "auto-generated spec, superseded by academy.spec"

# Build and cache output. All regenerated on demand.
drop "__pycache__"   "Python bytecode cache, regenerated automatically"
drop "build"         "PyInstaller working folder"
drop "dist"          "PyInstaller output — copy the exe out before removing"
drop ".venv"         "old shared environment, now per-platform"

echo
if [ "$total" = "0" ]; then
  printf "  %sNothing to clean. The folder is tidy.%s\n\n" "$grn" "$off"
  exit 0
fi

if [ "$APPLY" = "1" ]; then
  printf "  %sRemoved %d item(s).%s\n\n" "$grn" "$total" "$off"
else
  printf "  %d item(s) would be removed.\n" "$total"
  printf "  %sRun ./cleanup.sh --apply to do it.%s\n\n" "$dim" "$off"
fi

echo "  Kept on purpose"
echo "  ---------------"
echo "    academy.db      your records — back this up"
echo "    .env            signing key — losing it invalidates every card"
echo "    cards/          generated member cards, rebuilt when you reissue"
echo "    photos/         client photos, not recoverable if deleted"
echo "    .venv-*/        one environment per platform, rebuilt on next start"
echo
